# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Which-Cached
version:      1.02
version_from: lib/File/Which/Cached.pm
installdirs:  site
requires:
    Benchmark::Timer:              0
    File::Which:                   0
    Smart::Comments:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
